name: version_checker
description: A Flutter plugin for checking app version updates with customizable dialogs and API integration.
version: 1.0.0
homepage: https://github.com/aymanalareqi/version_checker

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  package_info_plus: ^4.2.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9

flutter:
  plugin:
    platforms:
      android:
        package: com.smartfingers.version_checker
        pluginClass: VersionCheckerPlugin
      ios:
        pluginClass: VersionCheckerPlugin

topics:
  - version-check
  - app-update
  - flutter-plugin
  - api-integration
